### ISSUE TITLE
请教一些问题

### ISSUE THREAD

**Issue by yangmingchuan** [fuusy/wanandroid_jetpack_kt#2]
1. BaseVmActivity和 BaseActivity 我没有搞懂两者有啥区别
2. BaseRepository 真的有存在的必要么？感觉只要有一个baseViewModel就可以了，
3. 体量偏小，很多功能我看没有实现
4. 不知是手机原因？我切换这个bottomTab的时候 会有卡顿。。

**Comment by fuusy** [comment]
1.BaseVmActivity在第一版没有加入Koin依赖注入时，内部封装了一个ViewModel，作子类Activity实现用，加入Koin后就删除了；
2.ViewModel是主要负责数据处理和View层与Model层的交互；
3.该项目主要以学习组件化和Jetpack为主，我的初衷是项目越小越好，如果后续有涉及Jetpack组件的需求，则考虑再添加功能；
4.Navigation组件有个问题在于每次切换Tab时，会重走onCreate，解决方案是自定义FragmentNavigator，将内部replace替换为show/hide

**Comment by yangmingchuan** [comment]
学到了 666
