### ISSUE TITLE
关于dependencies.gradle的问题

### ISSUE THREAD

**Issue by jiangnan11** [fuusy/wanandroid_jetpack_kt#3]
你好，这个项目非常好，已经star，我在学习该项目时，看到dependencies.gradle相关配置，我新建一个项目参照该项目进行dependencies.gradle配置，但是配置后项目不能运行，请问有哪些注意的地方吗？谢谢

**Comment by fuusy** [comment]
感谢start，请把具体的报错信息贴出来，
dependencies.gradle主要是将各个Module build.gradle的公共部分提取出来作统一处理，
记得子Moudle的build.gradle里要加上 apply from:'../dependencies.gradle'

**Comment by jiangnan11** [comment]
各种搜，各种尝试，又解决了，感谢回答。
 这样每个模块都引用dependencies.gradle，会不会使apk包增大呢？

**Comment by fuusy** [comment]
不会的，dependencies.gradle只是公共部分

**Comment by jiangnan11** [comment]
好的，感谢回答
