### ISSUE TITLE
协程多请求处理

### ISSUE THREAD

**Issue by scsfwgy** [fuusy/wanandroid_jetpack_kt#5]
关于BaseRepository#executeResp
封装的挺好的，在学习这个东西。有以下问题：

1.现在这个封装和LiveData绑定在一起。比如我想只想使用协程去做网络请求，而不是和LiveData绑定在一起，就很麻烦。能否剥离出来？
2.组合请求，比如两个请求A、B,必须两个结果拿到后一起渲染。这个封装该怎么操作。同样的，先请求A,再根据A的请求结果去请求B,怎么处理。这种需求就是对应的Rx里面的zip,flat。

**Comment by fuusy** [comment]
1.该项目主要是学Jetpack，LiveData暂不能剥离。如果你想只使用协程，只能自己封装个数据与UI通信的组件；2.协程Flow里有zip，flatMapMerge等操作符可以满足你的需求

**Comment by zhupengxiang** [comment]
executeResp方法里面传个flow进来感觉就方便多了
